image:
  repository: "leojaardim/appzinha"
  tag: "v1.0.2"

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  className: "nginx"  # Coloque o nome da sua IngressClass, se necessário
  annotations: {}
  hosts:
    - host: "appzinha.leonardo.jardim"  # Substitua pelo domínio desejado
      paths:
        - path: /
          pathType: Prefix
  tls: []  # Configurações TLS, se necessário
